version: 2
jobs:
  deploy:
    docker:
      - image: circleci/ruby:2.7.1
        environment:
          USER_NAME: dixonsiu
          USER_EMAIL: dixon.siu@gmail.com
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: install builder
          command : |
            gem install bundler
      - run: bundle install --path vendor/bundle
      - run: 
          name: Link Bundle Path
          command : |
            bundle --path vendor/bundle
      - run:
          name: Precompile Assets
          command: bundle exec jekyll build
      - deploy:
          name: Deploy Release to GitHub
          command: |
            if [ $CIRCLE_BRANCH == 'source' ]; then
              bash .circleci/deploy.sh
            fi
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - master
